# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'chatapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for chatapp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'SCLAlertView'

  # Facebook
  pod 'FBSDKLoginKit'

  # Google
  pod 'GoogleSignIn'
    

  target 'chatappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'chatappUITests' do
    # Pods for testing
  end

end
